config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :step_commands
  resources :exercise_steps
  resources :step_commands
  resources :exercise_steps
  resources :commands

  resources :steps #do

  resources :exercises #do

  get 'exercises/:id/steps', to: 'exercises#steps'
  get 'exercises/:id/steps/:id', to: 'steps#show'
  get 'exercises/:id/steps/:id/commands', to: 'steps#commands'

  root 'welcome#index'

end

app/models/exercise_step.rb
class ExerciseStep < ActiveRecord::Base
  belongs_to :exercises, :class_name => "Exercise", :foreign_key => "exercise_id"
  belongs_to :steps, :class_name => "Step", :foreign_key => "step_id"
end

app/controllers/exercise_steps_controller.rb
class ExerciseStepsController < ApplicationController
  before_action :set_exercise_step, only: [:show, :edit, :update, :destroy]

  # GET /exercise_steps
  # GET /exercise_steps.json
  def index
    @exercise_steps = ExerciseStep.all
  end

  # GET /exercise_steps/1
  # GET /exercise_steps/1.json
  def show
  end

  # GET /exercise_steps/new
  def new
    @exercise_step = ExerciseStep.new
  end

  # GET /exercise_steps/1/edit
  def edit
  end

  # POST /exercise_steps
  # POST /exercise_steps.json
  def create
    @exercise_step = ExerciseStep.new(exercise_step_params)

    respond_to do |format|
      if @exercise_step.save
        format.html { redirect_to @exercise_step, notice: 'Exercise step was successfully created.' }
        format.json { render :show, status: :created, location: @exercise_step }
      else
        format.html { render :new }
        format.json { render json: @exercise_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercise_steps/1
  # PATCH/PUT /exercise_steps/1.json
  def update
    respond_to do |format|
      if @exercise_step.update(exercise_step_params)
        format.html { redirect_to @exercise_step, notice: 'Exercise step was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise_step }
      else
        format.html { render :edit }
        format.json { render json: @exercise_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercise_steps/1
  # DELETE /exercise_steps/1.json
  def destroy
    @exercise_step.destroy
    respond_to do |format|
      format.html { redirect_to exercise_steps_url, notice: 'Exercise step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise_step
      @exercise_step = ExerciseStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_step_params
      params.require(:exercise_step).permit(:exercise_id, :step_id)
    end
end

app/helpers/exercise_steps_helper.rb
module ExerciseStepsHelper
end

app/views/exercise_steps/_form.html.erb
<%= form_for(@exercise_step) do |f| %>
  <% if @exercise_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise_step.errors.count, "error") %> prohibited this exercise_step from being saved:</h2>

      <ul>
      <% @exercise_step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :exercise_id %><br>
    <%= f.number_field :exercise_id %>
  </div>
  <div class="field">
    <%= f.label :step_id %><br>
    <%= f.number_field :step_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercise_steps/edit.html.erb
<h1>Editing Exercise Step</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise_step %> |
<%= link_to 'Back', exercise_steps_path %>

app/views/exercise_steps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Exercise Steps</h1>

<table>
  <thead>
    <tr>
      <th>Exercise</th>
      <th>Step</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercise_steps.each do |exercise_step| %>
      <tr>
        <td><%= exercise_step.exercise_id %></td>
        <td><%= exercise_step.step_id %></td>
        <td><%= link_to 'Show', exercise_step %></td>
        <td><%= link_to 'Edit', edit_exercise_step_path(exercise_step) %></td>
        <td><%= link_to 'Destroy', exercise_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exercise step', new_exercise_step_path %>

app/views/exercise_steps/new.html.erb
<h1>New Exercise Step</h1>

<%= render 'form' %>

<%= link_to 'Back', exercise_steps_path %>

app/views/exercise_steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Exercise:</strong>
  <%= @exercise_step.exercise_id %>
</p>

<p>
  <strong>Step:</strong>
  <%= @exercise_step.step_id %>
</p>

<%= link_to 'Edit', edit_exercise_step_path(@exercise_step) %> |
<%= link_to 'Back', exercise_steps_path %>