config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :step_commands
  resources :exercise_steps
  resources :step_commands
  resources :exercise_steps
  resources :commands

  resources :steps #do

  resources :exercises #do

  get 'exercises/:id/steps', to: 'exercises#steps'
  get 'exercises/:id/steps/:id', to: 'steps#show'
  get 'exercises/:id/steps/:id/commands', to: 'steps#commands'

  root 'welcome#index'

end

app/models/step_command.rb
class StepCommand < ActiveRecord::Base
  belongs_to :steps, :class_name => "Step", :foreign_key => "step_id"
  belongs_to :commands, :class_name => "Command", :foreign_key => "command_id"
end

app/controllers/step_commands_controller.rb
class StepCommandsController < ApplicationController
  before_action :set_step_command, only: [:show, :edit, :update, :destroy]

  # GET /step_commands
  # GET /step_commands.json
  def index
    @step_commands = StepCommand.all
  end

  # GET /step_commands/1
  # GET /step_commands/1.json
  def show
  end

  # GET /step_commands/new
  def new
    @step_command = StepCommand.new
  end

  # GET /step_commands/1/edit
  def edit
  end

  # POST /step_commands
  # POST /step_commands.json
  def create
    @step_command = StepCommand.new(step_command_params)

    respond_to do |format|
      if @step_command.save
        format.html { redirect_to @step_command, notice: 'Step command was successfully created.' }
        format.json { render :show, status: :created, location: @step_command }
      else
        format.html { render :new }
        format.json { render json: @step_command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /step_commands/1
  # PATCH/PUT /step_commands/1.json
  def update
    respond_to do |format|
      if @step_command.update(step_command_params)
        format.html { redirect_to @step_command, notice: 'Step command was successfully updated.' }
        format.json { render :show, status: :ok, location: @step_command }
      else
        format.html { render :edit }
        format.json { render json: @step_command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /step_commands/1
  # DELETE /step_commands/1.json
  def destroy
    @step_command.destroy
    respond_to do |format|
      format.html { redirect_to step_commands_url, notice: 'Step command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step_command
      @step_command = StepCommand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_command_params
      params.require(:step_command).permit(:step_id, :command_id)
    end
end

app/helpers/step_commands_helper.rb
module StepCommandsHelper
end

app/views/step_commands/_form.html.erb
<%= form_for(@step_command) do |f| %>
  <% if @step_command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step_command.errors.count, "error") %> prohibited this step_command from being saved:</h2>

      <ul>
      <% @step_command.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :step_id %><br>
    <%= f.number_field :step_id %>
  </div>
  <div class="field">
    <%= f.label :command_id %><br>
    <%= f.number_field :command_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/step_commands/edit.html.erb
<h1>Editing Step Command</h1>

<%= render 'form' %>

<%= link_to 'Show', @step_command %> |
<%= link_to 'Back', step_commands_path %>

app/views/step_commands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Step Commands</h1>

<table>
  <thead>
    <tr>
      <th>Step</th>
      <th>Command</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @step_commands.each do |step_command| %>
      <tr>
        <td><%= step_command.step_id %></td>
        <td><%= step_command.command_id %></td>
        <td><%= link_to 'Show', step_command %></td>
        <td><%= link_to 'Edit', edit_step_command_path(step_command) %></td>
        <td><%= link_to 'Destroy', step_command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step command', new_step_command_path %>

app/views/step_commands/new.html.erb
<h1>New Step Command</h1>

<%= render 'form' %>

<%= link_to 'Back', step_commands_path %>

app/views/step_commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Step:</strong>
  <%= @step_command.step_id %>
</p>

<p>
  <strong>Command:</strong>
  <%= @step_command.command_id %>
</p>

<%= link_to 'Edit', edit_step_command_path(@step_command) %> |
<%= link_to 'Back', step_commands_path %>