config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :step_commands
  resources :exercise_steps
  resources :step_commands
  resources :exercise_steps
  resources :commands

  resources :steps #do

  resources :exercises #do

  get 'exercises/:id/steps', to: 'exercises#steps'
  get 'exercises/:id/steps/:id', to: 'steps#show'
  get 'exercises/:id/steps/:id/commands', to: 'steps#commands'

  root 'welcome#index'

end

app/models/command.rb
class Command < ActiveRecord::Base
  has_many :step_commands
  has_many :steps, through: :step_commands
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
    respond_to do |format|
      format.html { @commands }
      format.json { render json: @commands, each_serializer: CommandsSerializer }
    end
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params
      params.require(:command).permit(:name, :argument, :color)
    end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :argument %><br>
    <%= f.text_field :argument %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/edit.html.erb
<h1>Editing Command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

app/views/commands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Commands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Argument</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @commands.each do |command| %>
      <tr>
        <td><%= command.name %></td>
        <td><%= command.argument %></td>
        <td><%= command.color %></td>
        <td><%= link_to 'Show', command %></td>
        <td><%= link_to 'Edit', edit_command_path(command) %></td>
        <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command', new_command_path %>

app/views/commands/new.html.erb
<h1>New Command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @command.name %>
</p>

<p>
  <strong>Argument:</strong>
  <%= @command.argument %>
</p>

<p>
  <strong>Color:</strong>
  <%= @command.color %>
</p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>